---
- hosts: pve-0.manpk.nl
  gather_facts: no
  name: "create VM template"
  vars:
    storage: pve-0-lvm
    vm:
      cloud_image_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
      cloud_image_path: /tmp/ubuntu-2004-server-amd64.qcow2
      template_id: 1001
      template_name: ubuntu-2004-cloudinit-template
      template_memory: 4096
  tasks:
    - name : download cloud image
      get_url:
        url: "{{ vm.cloud_image_url }}"
        dest: "{{ vm.cloud_image_path }}"
        mode: 0700

    - name: install packages
      command: "apt update -y && apt install libguestfs-tools -y"

    - name: install package in img
      command: "virt-customize -a focal-server-cloudimg-amd64.img --install qemu-guest-agent"

    - name: create a VM to use as a template
      command: "qm create {{ vm.template_id }} --name {{ vm.template_name }} --memory {{ vm.template_memory }} --net0 virtio,bridge=vmbr0"

    - name: import disk image
      command: "qm importdisk {{ vm.template_id }} {{ vm.cloud_image_path }} {{ storage }}"

    - name: configure VM to use imported image
      command: "qm set {{ vm.template_id }} --scsihw virtio-scsi-pci --scsi0 {{ storage }}:vm-{{ vm.template_id }}-disk-0"

    - name: add cloud-init image as CDROM
      command: "qm set {{ vm.template_id }} --ide2 {{ storage }}:cloudinit"

    - name: configure boot from the image
      command: "qm set {{ vm.template_id }} --boot c --bootdisk scsi0"

    - name: attach serial console
      command: "qm set {{ vm.template_id }} --serial0 socket --vga serial0"

    - name: create template
      command: "qm template {{ vm.template_id }}"
